-- Add Class Details to Users (for Students)
ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(50) DEFAULT 'CSE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS semester INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS section VARCHAR(10) DEFAULT 'A';
